### ISSUE TITLE
snmpwalk on nonexistent oid

### ISSUE THREAD

**Issue by mynever** [normanuber/ezsnmp#1]
Good day. Thanks for this brilliant snmp lib.
When i try to snmpwalk on nonexsitent oid i'm getting segfault.
```
Python 2.7.10 (default, Mar 16 2016, 16:34:50) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from easysnmp import snmp_walk
>>> snmp_walk("sysDescr.1", hostname='xxx.xxx.xxx.xxx, community='xxx', version=2)
Segmentation fault
```
Everything is fine with python 3.4 - i'm getting an empty list.

Debug info:
> netsnmp_walk: Starting
> netsnmp_walk: Arguments parsed
> netsnmp_walk: Getting session context
> Getting session ptr
> getting session capsule
> Got session capsule
> netsnmp_walk: Got session context
> netsnmp_walk: Loading operation data
> netsnmp_walk: Reading oids from varlist
> netsnmp_walk: Initial oid(sysDescr) oid_idx(1)
> netsnmp_walk: Finished loading operation data
> netsnmp_walk: Starting snmp request
> netsnmp_walk: filling request: oid(sysDescr) oid_idx(1) oid_arr_len(9) best_guess(0)
> netsnmp_walk: Sending pdu req
> netsnmp_walk: encountered end condition (next subtree iteration out of scope) var_len: 9/op_var_len: 9 var_name_size: 8/op_name_size: 8

**Comment by kamakazikamikaze** [comment]
@mynever Do you get the same error with the original package (Easysnmp)?

**Comment by mynever** [comment]
@kamakazikamikaze Everything is fine in original package. I'm getting an empty list.

```
Python 2.7.10 (default, Mar 16 2016, 16:34:50) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from easysnmp import snmp_walk
>>> snmp_walk("sysDescr.1", hostname='xxx.xxx.xxx.xxx', community='xxx', version=2)
[]
```

**Comment by normanuber** [comment]
Very odd that I never got these messages, but anyway I got some time and pushed a fix a while ago.
